### ISSUE TITLE
Developer listing

### ISSUE THREAD

**Issue by WardBrian** [mitzimorris/stan-website#14]
Equivalent of https://mc-stan.org/about/team/

**Comment by mitzimorris** [comment]
per discussion in the Stan meeting:
 - we don't want to make the distinction between current and emeritus members.
 - the above page in the current Jekyll-based website hasn't been properly updated over the years

I think the best thing we can do here would be to link to the GitHub "People" page:  https://github.com/orgs/stan-dev/people

- developers past and present:  https://github.com/orgs/stan-dev/people
- collaborators past and present: https://github.com/orgs/stan-dev/outside-collaborators

Members of the organization get to choose their visibility, so this means that we don't have to worry about who wants to be listed and what they want their profile to be.

**Comment by wds15** [comment]
Minimising maintenance sounds great. So maybe change "About mc-stan.org" to "About the Stan project" and add a link in on of the sections. Given the options available, a link to https://github.com/orgs/stan-dev/people is probably easiest.
