### ISSUE TITLE
Local CmdStan installations section clarification

### ISSUE THREAD

**Issue by jgabry** [mitzimorris/stan-website#16]
(First of all, thank you for working on this. Looks great!) 

In [Local CmdStan installations](https://mitzimorris.github.io/stan-website/install/install.html#local-cmdstan-installations-for-cmdstanpy-cmdstanr-and-stan.jl) it says that both CmdStanPy and CmdStanR provide the function `show_versions`, which "shows all installed CmdStan versions". We don't actually have this function in CmdStanR (although I'm happy to add it) and I don't think the CmdStanPy one actually shows all installed CmdStan versions. Here's the output of `cmdstanpy.show_versions()`: 

```
>>> cmdstanpy.show_versions()
INSTALLED VERSIONS
---------------------
python: 3.7.4 (default, Sep  7 2019, 18:31:37) 
[Clang 9.0.0 (clang-900.0.39.2)]
python-bits: 64
OS: Darwin
OS-release: 24.1.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
cmdstan_folder: /Users/jgabry/.cmdstan/cmdstan-2.35.0
cmdstan: (2, 35)
cmdstanpy: 1.1.0
pandas: 1.3.5
xarray: None
tqdm: 4.66.1
numpy: 1.21.6
```

I have many different versions of CmdStan installed but this only lists the active one, plus all this other information.

**Comment by WardBrian** [comment]
The description of cmdstan_path is also wrong, I think — it doesn’t really show which version is being used, it tells you where the version you’re using is being located. By default this will contain the version number in a path, but it doesn’t need to
