### ISSUE TITLE
Should RStan be described as a "legacy interface"?

### ISSUE THREAD

**Issue by jgabry** [mitzimorris/stan-website#18]
I understand why you refer to RStan as the "Legacy R interface to Stan" since it doesn't support the latest Stan version(s). But using RStan is still the only way to get pre-compiled Stan models on CRAN, so for the ~100 packages that depend on RStan (and all their users) it's not really a legacy interface, it's the only interface they can use. Given that, I'm not sure how we should refer to RStan. Do other people have thoughts about this?

**Comment by mitzimorris** [comment]
the accompanying text clarifies that if you're starting a new project, use CmdStanR.  what is wrong with the term "legacy"?

**Comment by jgabry** [comment]
> the accompanying text clarifies that if you're starting a new project, use CmdStanR

If you're starting a new project that involves pre-compiled models you still need to use RStan (or you need to distribute the pre-compiled models yourself, which is very uncommon in the R world). So I was just saying  (perhaps I worded it poorly) that "legacy" makes sense except for in that scenario where RStan is basically the only option. I wasn't sure where to convey the info to users that RStan is still required in that use case, which isn't an uncommon one.

**Comment by mitzimorris** [comment]
I guess we mean different things here by "project" - what I mean is if you're planning to use Stan because you want to analyze your data, you should use CmdStanR.   the number of people building software is still very small compared to the number of people just using stan.

**Comment by WardBrian** [comment]
I think we can say cmdstanr is recommended for new users without saying RStan is legacy - to me, that implies it’s unmaintained, which it isn’t

**Comment by mitzimorris** [comment]
I think that new users should be strongly encouraged to use CmdStanR, unless

* we don't plan on maintaining CmdStanR any longer 
* RStan is now easy to install everywhere and is keeping up with the latest CmdStan release.

**Comment by mitzimorris** [comment]
changed the description of RStan as part of PR #19

**Comment by jgabry** [comment]
What if instead of "legacy interface" we say "original interface"?

**Comment by jgabry** [comment]
Oh just saw your PR, I'll comment over there.

**Comment by jgabry** [comment]
I said this in my brms PR, but I closed that one, so saying here: I hope I wasn't coming across as combative, I didn't intend to. The new site is fabulous!

**Comment by mitzimorris** [comment]
updated wording accordingly
