### ISSUE TITLE
minted for highlighting Stan code in LaTeX

### ISSUE THREAD

**Issue by avehtari** [mitzimorris/stan-website#22]
Stan Toolkit page has For LaTeX
> [lstbayes](https://github.com/jrnold/lstbayes)	LaTeX listings for Stan syntax highlighting.

But [minted](https://github.com/gpoore/minted) is much better, and as it's based on Pygments it will provide the same code highlighting, e.g., as Quarto

**Comment by mitzimorris** [comment]
added as part of PR https://github.com/mitzimorris/stan-website/pull/19
