### ISSUE TITLE
capture information from current website page: https://mc-stan.org/users/interfaces/

### ISSUE THREAD

**Issue by mitzimorris** [mitzimorris/stan-website#9]
In current mc-stan.org website, file `users/interfaces/index.md` lists a bunch of editors as well as interfaces.

Figure out where this should go in the new website, and update accordingly.

**Comment by WardBrian** [comment]
Editor information seems like it could live on the install page as well, toward the bottom?

**Comment by mitzimorris** [comment]
https://github.com/mitzimorris/stan-website/pull/11
